#!/usr/bin/python

import sys
file1 = sys.argv[1] #NPUTE imputation output
file2 = sys.argv[2] #*_noduplicates_isolate_order.csv [order of individuals space delimited generated by Concater2Npute.py]
file3 = sys.argv[3] #*_noduplicates_lociorder.csv

with open(file1,'r') as set1:
    count = 0
    seqs = {}
    for i in set1:
        i = i.rstrip()
        i = i.split(",")
        count += 1

        if "" not in i:
            sizei = len(i) #measure length of i only if imputation has not failed

        if "" in i: #if imputation has failed
            i = []
            for z in range(sizei):
                i.append("-") #set the whole locus as missing data

        for j in range(sizei): #for the number of columns
            if j not in seqs:
                seqs[j] = [i[j]]
            else:
                newseq = seqs[j]
                newseq.append(i[j])
                seqs[j] = newseq

with open(file2,'r') as set2:
    isolates = {}
    count1 = 0

    for i in set2:
        i = i.split(" ")
        for j in i:
            count1 += 1
            isolates[count1] = j

with open(file3,'r') as set3:
    lociorder = {}
    count2 = 0

    for i in set3:
        i = i.rstrip()
        count2 += 1
        lociorder[count2] = i

print len(lociorder)

count3 = 0
catalogfinal = {}
for i in seqs.items():
    locilist = []
    for j in range(0,len(i[1]),80):
        locilist.append("".join(i[1][j:j+80]))
    count3 += 1
    catalogfinal[count3] = locilist

#create output
output1 = open(file1.replace(".csv","_BAPS-MLST_input.csv"),"w")

lineloci = []
for i in lociorder.values():
    lineloci.append(i)

output1.write("ID ST "+" ".join(lineloci)+"\n"); #write header of the file

#write data
for i in catalogfinal.items():
    output1.write(isolates[i[0]]+" "+str(i[0])+" "+" ".join(i[1])+"\n");

output1.close()
